//
// Generated by Microsoft (R) D3DX9 Shader Assembler
//
//  Source: ps.psh
//  Flags: /Vd 
//


const DWORD g_ps11_main[] =
{
    0xffff0101, 0x00000042, 0xb00f0000, 0x00000001, 0x800f0000, 0xb0e40000, 
    0x0000ffff
};
