//
// Generated by Microsoft (R) D3DX9 Shader Assembler
//
//  Source: vs.vsh
//  Flags: /Vd 
//


const DWORD g_vs11_main[] =
{
    0xfffe0101, 0x00000001, 0xe00f0000, 0x90e40007, 0x00000001, 0x800f0000, 
    0xa0e40000, 0x00000004, 0xc00f0000, 0x90e40000, 0x80e40000, 0xa0e40001, 
    0x0000ffff
};
